// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ProductParserRulesController from "./product_parser_rules_controller"
application.register("product-parser-rules", ProductParserRulesController)
