# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/product_parser_rules', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # ProductParserRule. As you add validations to ProductParserRule, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      ProductParserRule.create! valid_attributes
      get product_parser_rules_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      product_parser_rule = ProductParserRule.create! valid_attributes
      get product_parser_rule_url(product_parser_rule)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_product_parser_rule_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      product_parser_rule = ProductParserRule.create! valid_attributes
      get edit_product_parser_rule_url(product_parser_rule)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new ProductParserRule' do
        expect do
          post product_parser_rules_url, params: { product_parser_rule: valid_attributes }
        end.to change(ProductParserRule, :count).by(1)
      end

      it 'redirects to the created product_parser_rule' do
        post product_parser_rules_url, params: { product_parser_rule: valid_attributes }
        expect(response).to redirect_to(product_parser_rule_url(ProductParserRule.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new ProductParserRule' do
        expect do
          post product_parser_rules_url, params: { product_parser_rule: invalid_attributes }
        end.to change(ProductParserRule, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post product_parser_rules_url, params: { product_parser_rule: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested product_parser_rule' do
        product_parser_rule = ProductParserRule.create! valid_attributes
        patch product_parser_rule_url(product_parser_rule), params: { product_parser_rule: new_attributes }
        product_parser_rule.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the product_parser_rule' do
        product_parser_rule = ProductParserRule.create! valid_attributes
        patch product_parser_rule_url(product_parser_rule), params: { product_parser_rule: new_attributes }
        product_parser_rule.reload
        expect(response).to redirect_to(product_parser_rule_url(product_parser_rule))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        product_parser_rule = ProductParserRule.create! valid_attributes
        patch product_parser_rule_url(product_parser_rule), params: { product_parser_rule: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested product_parser_rule' do
      product_parser_rule = ProductParserRule.create! valid_attributes
      expect do
        delete product_parser_rule_url(product_parser_rule)
      end.to change(ProductParserRule, :count).by(-1)
    end

    it 'redirects to the product_parser_rules list' do
      product_parser_rule = ProductParserRule.create! valid_attributes
      delete product_parser_rule_url(product_parser_rule)
      expect(response).to redirect_to(product_parser_rules_url)
    end
  end
end
